### ISSUE TITLE
支持etcd作为注册中心吗

### ISSUE THREAD

**Issue by SpringDay6** [yidongnan/grpc-spring-boot-starter#862] opened 2023-03-09 09:31 UTC
it's  register can support etcd ?

**Comment by ST-DDT** [comment] 2023-03-09 18:27
[English](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/862?_x_tr_sl=zh-TW&_x_tr_tl=en)

---

You need a spring-boot DiscoveryClient compatible implementation for etcd.
I'm not aware of an implementation right now, but I haven't searched for it in a while.

Duplicate of https://github.com/yidongnan/grpc-spring-boot-starter/issues/557

**Closed by ST-DDT** 2023-03-09 18:27 UTC
Labels: question
