### ISSUE TITLE
gprc wont support 3.1.0 version of springboot the service wont get activated , i have to degrade the version to 2.7.5

### ISSUE THREAD

**Issue by abhishek-vernekar** [yidongnan/grpc-spring-boot-starter#914] opened 2023-06-22 10:43 UTC
**The problem**

**The solution**

**Alternatives considered**

**Additional context**

**Comment by ST-DDT** [comment] 2023-06-22 13:18
Duplicate of https://github.com/yidongnan/grpc-spring-boot-starter/issues/778

**Closed by ST-DDT** 2023-06-22 13:18 UTC
Labels: enhancement
