### ISSUE TITLE
Grpc-spring-boot-starter SpringBoot3

### ISSUE THREAD

**Issue by wjohnst3** [yidongnan/grpc-spring-boot-starter#956] opened 2023-09-01 18:45 UTC
I've been using this starter in my project for sometime and am quite happy with it. I've been tasked with updating our SpringBoot dependencies to version 3. Unexpectedly, I see that this auto-starter only works in SpringBoot 2.x. Do you have a timeframe for SpringBoot 3 support?

**Comment by yidongnan** [comment] 2023-09-09 09:09
Duplicate of #778 (not released yet, just add the files yourself)

**Closed** 2023-09-09 09:10 UTC
Labels: question
