### ISSUE TITLE
I have an issue trying to run gRPC server on an available port

### ISSUE THREAD

**Issue by muraliweb9** [yidongnan/grpc-spring-boot-starter#896] opened 2023-05-25 13:21 UTC
Run gRPC server on an available port

Having an issue running with this in application.yml
````yaml
grpc:
  server:
    port: 0
````

````txt
Caused by: java.lang.NoClassDefFoundError: org/springframework/util/SocketUtils
	at net.devh.boot.grpc.server.config.GrpcServerProperties.getPort(GrpcServerProperties.java:429) ~[grpc-server-spring-boot-autoconfigure-2.14.0.RELEASE.jar:2.14.0.RELEASE]
	at net.devh.boot.grpc.server.config.GrpcServerProperties.hashCode(GrpcServerProperties.java:54) ~[grpc-server-spring-boot-autoconfigure-2.14.0.RELEASE.jar:2.14.0.RELEASE]
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:na]
	at java.base/java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[na:na]
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.requiresDestruction(PersistenceAnnotationBeanPostProcessor.java:399) ~[spring-orm-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.hasApplicableProcessors(DisposableBeanAdapter.java:417) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.requiresDestruction(AbstractBeanFactory.java:1850) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.registerDisposableBeanIfNecessary(AbstractBeanFactory.java:1867) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:638) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.8.jar:6.0.8]
	... 81 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.util.SocketUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 91 common frames omitted
````

Which versions do you use?
* Spring (boot): 3.0.6
* grpc-java: <grpc.version>1.55.1</grpc.version>
* grpc-spring-boot-starter: 3.0.6
* java: version + architecture (64bit?) 17 64bit

````xml
<properties>
        <java.version>17</java.version>
        <spring-boot-admin.version>3.0.2</spring-boot-admin.version>
        <spring-cloud.version>2022.0.2</spring-cloud.version>
        <grpc.version>1.55.1</grpc.version>
        <protobuf.version>3.23.1</protobuf.version>
        <spotless-plugin.version>2.36.0</spotless-plugin.version>
        <jacoco.version>0.8.8</jacoco.version>
    </properties>
````

This stack trace question gives an idea of the cause:
https://stackoverflow.com/questions/74632141/spring-boot-3-upgrade-java-lang-noclassdeffounderror-org-springframework-util

````txt
Caused by: java.lang.NoClassDefFoundError: org/springframework/util/SocketUtils
	at net.devh.boot.grpc.server.config.GrpcServerProperties.getPort(GrpcServerProperties.java:429) ~[grpc-server-spring-boot-autoconfigure-2.14.0.RELEASE.jar:2.14.0.RELEASE]
````

org/springframework/util/SocketUtils is not available in Spring 3.X - is there a work around

**Comment by muraliweb9** [comment] 2023-05-25 14:20
As a work around I did this:

`import net.devh.boot.grpc.server.config.GrpcServerProperties;
**import org.springframework.cloud.function.utils.SocketUtils;**
import org.springframework.context.annotation.Configuration;

@Configuration
public class GrpcServerProperties2 extends GrpcServerProperties {

    private int port = 9090;

    @Override
    public int getPort() {
        if (this.port == 0) {
            this.port = SocketUtils.findAvailableTcpPort();
        }
        return this.port;
    }

    public void setPort(int port) {
        super.setPort(port);
        this.port = port;
    }
}`

**Comment by dsyer** [comment] 2023-05-30 14:09
Duplicates #826

**Comment by ST-DDT** [comment] 2023-06-01 21:47
Duplicate of #826

**Closed by ST-DDT** 2023-06-01 21:47 UTC
Labels: question
