### ISSUE TITLE
Server processing duration metric not updated for cancellations

### ISSUE THREAD

**Issue by steven-sheehy** [yidongnan/grpc-spring-boot-starter#438] opened 2020-10-21 20:10 UTC
**The context**

I want to be able to get `grpc.server.processing.duration` metrics for long lived server streaming gRPC calls where the client can cancel the stream at any time. Since the server stream is potentially infinite in my case (e.g. it never calls complete), the only way for the client to stop it is with a cancel.

**The bug**

Metrics are not being updated for cancel. They are being correctly being updated for completions and errors. 

**Stacktrace and logs**

After invoking and cancelling a server streaming api 3 times:
```
 ~> curl -s "http://localhost:8081/actuator/prometheus" | grep -E "^grpc_server_processing_duration_seconds"
grpc_server_processing_duration_seconds_count{application="hedera-mirror-grpc",method="subscribeTopic",methodType="SERVER_STREAMING",service="com.hedera.mirror.api.proto.ConsensusService",statusCode="OK",} 0.0
grpc_server_processing_duration_seconds_sum{application="hedera-mirror-grpc",method="subscribeTopic",methodType="SERVER_STREAMING",service="com.hedera.mirror.api.proto.ConsensusService",statusCode="OK",} 0.0
grpc_server_processing_duration_seconds_max{application="hedera-mirror-grpc",method="subscribeTopic",methodType="SERVER_STREAMING",service="com.hedera.mirror.api.proto.ConsensusService",statusCode="OK",} 0.0
```

**Steps to Reproduce**

1. Invoke a server streaming API
2. Cancel request to server
3. view the metrics

**The application's environment**

Which versions do you use?
* Spring (boot): 2.3.3.RELEASE
* grpc-java: 1.31.1
* grpc-spring-boot-starter: 2.7.0.RELEASE
* java: version + architecture (64bit?): OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**Additional context**

* Did it ever work before? No
* Do you have a demo?

**Comment by steven-sheehy** [comment] 2020-10-21 20:17
I tested with 2.10.1.RELEASE as well with the same result. I debugged the server and `MetricCollectingServerCall.close()` is never invoked for cancel so the timer sample is never stopped and recorded.

**Comment by ST-DDT** [comment] 2020-10-22 06:54
We probably forgot to listen to the [ServerCall.Listener#onCancelled()](https://github.com/grpc/grpc-java/blob/f5c7f4e15440cb0461a61afd6c0504f248e95af0/api/src/main/java/io/grpc/ServerCall.java#L78).
Thanks for reporting this issue. We will fix that asap.

**Comment by ST-DDT** [comment] 2020-10-30 15:07
@steven-sheehy @yidongnan : In the response to the upstream issue, it is said, that the `ServerCall#close` is called after the request is processed, but before the response has been sent to the client. So should the metric only measure the time taken for the actual processing or should the network sent delay be included? I assume this should be roughly a few ms, but according to the response `it can be a long time (minutes or hours)` (scary)...

This is relevant for fixing this issue because:
- If the network part is excluded, then the `Listener` will invoke the `ServerCall` instance to report the cancellation to actuator.
- Otherwise, the `ServerCall` will report the status to the `Listener` and only on completion/cancellation will it be reported to actuator.

We currently use the first variant (without reporting the cancellations), but if we fix that, then we might count calls twice if they get cancelled right after `ServerCall#close` is called. IMO using the second variant is probably the best.
Or should we record both times, so that we could theoretically measure the network overhead for those calls?

> - `grpc.server.processing.duration`: `The total time taken for the server to process the call (excluding network overhead)`
> - `grpc.server.completion.duration`: `The total time taken for the server to complete the call (including network sent)`

**Comment by steven-sheehy** [comment] 2020-10-30 15:33
I think the second approach is best to rely only on the Listener for onComplete/onCancel. This is also in keeping with the definition of the metric as the "processing" duration and not including the network overhead. If you're worried about duplicate metrics you can always store a `boolean recorded` class variable with the Timer.Sample so you can keep it from recording a second time.

I don't think the completion metrics are useful as it sounds like a corner case or it can be considered for a future enhancement.

**Comment by ST-DDT** [comment] 2020-10-30 15:41
For clarification: `Listener#onCompletion` is including network overhead, `ServerCall#close` is without network overhead.

**Comment by ST-DDT** [comment] 2020-10-30 20:12
Something strange happened while testing my fix for this issue.
I can no longer proof that the initial statement is true:

> I debugged the server and `MetricCollectingServerCall.close()` is never invoked for cancel so the timer sample is never stopped and recorded.

(In the upstream issue I used a broken `ServerCall.Listener` implementation, which coincidentally caused the same error. I forgot to call `super` in the listener)

Could you test your code again?
If the bug still applies to you, please try to create a unit test for me to reproduce the error, potentially based on this branch:
https://github.com/yidongnan/grpc-spring-boot-starter/compare/metrics/cancellations2#diff-2ffa69ca45fc9523a26a6c604fca2977aaba053a1616166b2fca6cc588d3698aR55

**Comment by steven-sheehy** [comment] 2020-11-04 22:52
```proto
rpc echo(stream google.protobuf.Empty) returns (stream google.protobuf.Empty) {}
```

Your test has a bidirectional stream rpc. My scenario is a server streaming rpc. Try adding the below:

```proto
rpc serverStream(google.protobuf.Empty) returns (stream google.protobuf.Empty) {}
```

When I did so and changed `MetricCollectingInterceptorTest` to use that it failed.

**Comment by ST-DDT** [comment] 2020-11-06 23:22
Thanks for your feedback. I'll try to test and fix it in a few days.

**Closed** 2020-11-12 03:34 UTC
Labels: bug, feedback required
