### ISSUE TITLE
客户端和服务端在同一个项目中，出现的"this.stub is null"问题

### ISSUE THREAD

**Issue by hanweidong** [yidongnan/grpc-spring-boot-starter#886] opened 2023-05-08 07:37 UTC
**The context**

What do you wish to achieve?

**The question**

你好，我尝试在一个项目中启动客户端和服务端，当我调用client的controller发送消息时，提示"this.stub" is null，麻烦问一下这是怎么回事哈

**The application's environment**

Which versions do you use?
* Spring (boot): 3.0.6
* grpc-java: 3.22.0
* grpc-spring-boot-starter: 2.14.0.RELEASE
* java: version + architecture (64bit?) 17
* Other relevant libraries...

**Additional information**

* How can we reproduce it?
我的application.yaml文件如下：
```
grpc:
  server:
    port: 9898
  client:
    local-grpc-server:
      address: static://127.0.0.1:9898
      negotiationType: plaintext
```
grpc client如下：
```
@Service
public class GrpcClientService {

  @GrpcClient("local-grpc-server")
  private RPCAlertServiceGrpc.RPCAlertServiceBlockingStub stub;

  public String sendMessage() {
    RPCAlertRequest request = RPCAlertRequest.newBuilder()
      .setEventType(EventType.DATA_COLLECT)
      .setEventLevel(EventLevel.HIGH)
      .build();
    RPCAlertResponse response = stub.sendEventStatus(request);
    return response.getMessage();
  }
}
```

**Comment by ST-DDT** [comment] 2023-05-08 07:48
Duplicate of https://github.com/yidongnan/grpc-spring-boot-starter/pull/775#issuecomment-1329023335

**Comment by hanweidong** [comment] 2023-05-08 08:03
> Duplicate of [#775 (comment)](https://github.com/yidongnan/grpc-spring-boot-starter/pull/775#issuecomment-1329023335)

你好，这个问题现在应该如何解决呢，我看到[QB-NemanjaTozic]提供的链接已经失效了(https://github.com/QB-NemanjaTozic)https://github.com/NemanjaT/airsoft-iam/blob/main/src/main/java/com/ntozic/airsoft/iam/config/grpc/GrpcConfig.java

**Comment by hanweidong** [comment] 2023-05-08 08:28
> Duplicate of [#775 (comment)](https://github.com/yidongnan/grpc-spring-boot-starter/pull/775#issuecomment-1329023335)

我尝试添加了配置类,但是在启动spring服务时提示Caused by: java.lang.IllegalStateException: Found duplicate service implementation: RPCAlertService
```
@Configuration
@ImportAutoConfiguration({
  net.devh.boot.grpc.client.autoconfigure.GrpcClientAutoConfiguration.class,
  net.devh.boot.grpc.client.autoconfigure.GrpcClientMetricAutoConfiguration.class,
  net.devh.boot.grpc.client.autoconfigure.GrpcClientHealthAutoConfiguration.class,
  net.devh.boot.grpc.client.autoconfigure.GrpcClientSecurityAutoConfiguration.class,
  net.devh.boot.grpc.client.autoconfigure.GrpcClientTraceAutoConfiguration.class,
  net.devh.boot.grpc.client.autoconfigure.GrpcDiscoveryClientAutoConfiguration.class,

  net.devh.boot.grpc.common.autoconfigure.GrpcCommonCodecAutoConfiguration.class,
  net.devh.boot.grpc.common.autoconfigure.GrpcCommonTraceAutoConfiguration.class,

  net.devh.boot.grpc.server.autoconfigure.GrpcAdviceAutoConfiguration.class,
  net.devh.boot.grpc.server.autoconfigure.GrpcHealthServiceAutoConfiguration.class,
  net.devh.boot.grpc.server.autoconfigure.GrpcMetadataConsulConfiguration.class,
  net.devh.boot.grpc.server.autoconfigure.GrpcMetadataEurekaConfiguration.class,
  net.devh.boot.grpc.server.autoconfigure.GrpcMetadataNacosConfiguration.class,
  net.devh.boot.grpc.server.autoconfigure.GrpcMetadataZookeeperConfiguration.class,
  net.devh.boot.grpc.server.autoconfigure.GrpcReflectionServiceAutoConfiguration.class,
  net.devh.boot.grpc.server.autoconfigure.GrpcServerAutoConfiguration.class,
  net.devh.boot.grpc.server.autoconfigure.GrpcServerFactoryAutoConfiguration.class,
  net.devh.boot.grpc.server.autoconfigure.GrpcServerMetricAutoConfiguration.class,
  net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration.class,
  net.devh.boot.grpc.server.autoconfigure.GrpcServerTraceAutoConfiguration.class
})
public class GrpcConfig {
}
```

**Comment by ST-DDT** [comment] 2023-05-08 08:31
Full stacktrace please!

**Comment by hanweidong** [comment] 2023-05-08 08:39
> 请完整堆栈跟踪！

你好，以下是完整的堆栈信息：
```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-05-08T16:38:23.722+08:00 ERROR 22868 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'shadedNettyGrpcServerLifecycle'
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:934)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:587)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
	at com.hikvision.bigdata.ai.nepf.server.NepfServerApplication.main(NepfServerApplication.java:18)
Caused by: java.lang.IllegalStateException: Found duplicate service implementation: RPCAlertService
	at net.devh.boot.grpc.server.serverfactory.AbstractGrpcServerFactory.configureServices(AbstractGrpcServerFactory.java:106)
	at net.devh.boot.grpc.server.serverfactory.AbstractGrpcServerFactory.configure(AbstractGrpcServerFactory.java:85)
	at net.devh.boot.grpc.server.serverfactory.AbstractGrpcServerFactory.createServer(AbstractGrpcServerFactory.java:67)
	at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.createAndStartGrpcServer(GrpcServerLifecycle.java:111)
	at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.start(GrpcServerLifecycle.java:72)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	... 13 common frames omitted

```

**Comment by ST-DDT** [comment] 2023-05-08 13:46
Looks like you have the RPCAlertService twice.
Maybe as an annotated bean and in a @Configuration bean?

**Closed** 2023-05-26 20:33 UTC
Labels: question
