### ISSUE TITLE
Please upgrade to the recent version of gRPC-java dependencies

### ISSUE THREAD

**Issue by ngrigoriev** [yidongnan/grpc-spring-boot-starter#203] opened 2019-03-20 13:34 UTC
If possible, could you please upgrade the version of grpc-java? Version 1.1.19 fixes a couple of things, including some annoying warnings on JDK 11.

Thanks!

**Comment by ST-DDT** [comment] 2019-03-20 13:58
Thanks for pointing this out. In the meantime you can use import the `grpc-bom` and overwrite the version definitions yourself. For Maven you can do that with:

````xml
<dependency>
	<groupId>io.grpc</groupId>
	<artifactId>grpc-bom</artifactId>
	<version>1.19.0</version>
	<type>pom</type>
	<scope>import</scope>
</dependency>
````

**Comment by ST-DDT** [comment] 2019-04-08 14:30
Detected incompatibility: https://github.com/grpc/grpc-java/issues/5556
I'll take care of that.

**Comment by ST-DDT** [comment] 2019-04-10 18:20
The incompatibility was caused by an upstream bug and is fixed in 1.20.

**Comment by ST-DDT** [comment] 2019-04-10 18:20
Work in progress for grpc-java update to 1.19

**Comment by ST-DDT** [comment] 2019-04-11 07:32
@yidongnan I found a small issue while trying to update to grpc-java 1.19. 

We have the following options:

* Stay incompatible to 1.19, but be compatible with prior versions (1.17 & 1.18) and 1.20
  * The client security section would still be incompatible with pre 1.19 options
* Or upgrade to 1.19 and drop the entire client-side support for pre 1.19 versions, but be compatible with more future versions.
  * This will essentially remove all deprecated code usage

Which option should we use?

**Comment by yidongnan** [comment] 2019-04-11 10:49
> The client security section would still be incompatible with pre 1.19 options
You are referring the incompatible problem is passed by custom attributes in NameResolver.Helper?

**Comment by ST-DDT** [comment] 2019-04-11 12:47
>> The client security section would still be incompatible with pre 1.19 options
>
> The incompatibility you are referring to is a problem in NameResolver.Helper that can't pass custom attributes?

The `CallCredentials` class has been renamed from `CallCredentials2` to `CallCredentials`. In previous versions of grpc this class was an interface and thus the change is incompatible ABI wise.

>> Or upgrade to 1.19 and drop the entire client-side support for pre 1.19 versions, but be compatible with more future versions.
>
> In this option, use NameResolverRegistry in 1.21 , which is not compatible with all previous versions. Do you mean this?

AFAICT `NameResolverRegistry` is not yet present and even if it would be, it would still not solve our problem, as we would still try to call a method that is not yet present.

grpc-java 1.19.0 changed a method in API and ABI incompatible way.
(They changed a method signature without providing a bridging method.)

````diff
- public NameResolver newNameResolver(URI targetUri, Attributes params) {
+ public NameResolver newNameResolver(URI targetUri, Helper helper) {
````

If we follow the change, we loose the pre 1.19 support.
If we don't, we aren't compatible with 1.19.

**Comment by yidongnan** [comment] 2019-04-11 13:09
Thank you for your explanation. In contrast, I prefer the first option. Stay incompatible to 1.19, but be compatible with prior versions (1.17 & 1.18) and 1.20

**Comment by yidongnan** [comment] 2019-04-13 15:15
I have a closer look at the changes to grpc-java. It may seem feasible to choose the first method in the short term, but it is highly probable that there will be incompatibilities in later versions. So now I prefer the second way. Better a little loss than a long sorrow. Do you have any suggestions? @ST-DDT

**Closed** 2019-04-20 23:31 UTC
Labels: enhancement, incompatibility
