### ISSUE TITLE
Are there any plans to release a new version that supports protobuf 3.13.x?

### ISSUE THREAD

**Issue by sreenidhy** [yidongnan/grpc-spring-boot-starter#464] opened 2020-12-10 21:42 UTC
**The context**

What do you wish to achieve?

I'd like to use some protobuf 3.13 features in my project.

**The question**

What's the problem? What's not working? What's missing and why do you need it?

My project depends on grpc-spring-boot-starter library. I see that the [latest](https://github.com/yidongnan/grpc-spring-boot-starter/releases/tag/v2.10.1.RELEASE) release of this project still uses 3.12.4. Are there plans to release a new version that works with protobuf 3.13.x? If not, I'd love to have a version of grpc-spring-boot-starter that works with 3.13.x.

**Stacktraces and logs**

Do you have any relevant stacktraces or logs of your attempts?
I haven't attempted to bump the protobuf version to 3.13.x while still using grpc-sping-boot-starter 2.9.0 in my project. I was unsure if something might break. So, I do not have any more data on what might happen if I went ahead and updated the protobuf version in my project.

**The application's environment**

Which versions do you use?
* Spring (boot): 2.3.1
* grpc-java: 1.30
* grpc-spring-boot-starter: 2.9.0
* java: version + architecture (64bit?) - 12 / 64bit
* Other relevant libraries...

**Additional information**

* Did it ever work before?
* How can we reproduce it?
* Do you have a demo?

**Comment by ST-DDT** [comment] 2020-12-10 23:09
> My project depends on grpc-spring-boot-starter library. I see that the latest release of this project still uses 3.12.4. Are there plans to release a new version that works with protobuf 3.13.x? If not, I'd love to have a version of grpc-spring-boot-starter that works with 3.13.x.

This library probably also works with 3.13.x. The most important part for the compatibility is actually grpc-java.
If this library is compatible to a grpc-java version, then it's also compatible to any protobuf version that those support. I'm not aware of any breaking changes/compatibility issues in either of these so far.

I hope to have some time to fix/implement the remaining issues during the upcoming holidays.
And I will probably update to the latest versions as well.

Does this answer your questsion?

**Comment by sreenidhy** [comment] 2020-12-10 23:15
Great, thanks for the response. That answers my question. Looking forward to the new release with updated version of grpc-java and protobuf. Happy holidays!

**Comment by skoret** [comment] 2020-12-17 09:42
Hi! It looks like `grpc-spring-boot-starter` is no longer compatible with `grpc-java` since [v1.33.0](https://github.com/grpc/grpc-java/releases/tag/v1.33.0).
I made [simple project](https://github.com/skoret/grpc-spring-boot-starter-example) with reproducible error. afaict, breaking change is:
> • api, core: delete io.grpc.LoadBalancer.loadBalancingConfig attribute (#7440). The attribute was deprecated in v1.27.0, now it is completely deleted.
Hope this helps. Stacktrace for [test](https://github.com/skoret/grpc-spring-boot-starter-example/blob/master/src/test/java/org/example/echo/EchoServiceTest.java#L17) in my repo:
```
2020-12-17 12:35:09.275  INFO [main||] echo.EchoServiceTest - Starting EchoServiceTest using Java 11.0.9.1 on pc.local with PID 7171 (started by skoret in /Users/skoret/tmp/grpc-spring-boot-starter-example)
2020-12-17 12:35:09.279  INFO [main||] echo.EchoServiceTest - No active profile set, falling back to default profiles: default
2020-12-17 12:35:09.702  INFO [main||] autoconfigure.GrpcServerFactoryAutoConfiguration - 'grpc.server.in-process-name' is set: Creating InProcessGrpcServerFactory
2020-12-17 12:35:09.851  INFO [main||] serverfactory.AbstractGrpcServerFactory - Registered gRPC service: org.example.echo.proto.EchoService, bean: echoApplication.EchoService, class: org.example.echo.EchoApplication$EchoService
2020-12-17 12:35:09.859  INFO [main||] serverfactory.GrpcServerLifecycle - gRPC Server started, listening on address: in-process:echoService, port: -1
2020-12-17 12:35:09.867  INFO [main||] echo.EchoServiceTest - Started EchoServiceTest in 0.789 seconds (JVM running for 7.182)
2020-12-17 12:35:09.878  INFO [main||] nameresolver.NameResolverRegistration - net.devh.boot.grpc.server.nameresolver.SelfNameResolverFactory@64da6cbd is available -> Added to the NameResolverRegistry
2020-12-17 12:35:09.881  INFO [main||] autoconfigure.GrpcClientAutoConfiguration - Detected grpc-netty-shaded: Creating ShadedNettyChannelFactory + InProcessChannelFactory
2020-12-17 12:35:10.193 ERROR [main||] internal.ManagedChannelImpl - [Channel<2>: (directaddress:///echoService)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.NoSuchFieldError: ATTR_LOAD_BALANCING_CONFIG
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.tryHandleResolvedAddresses(AutoConfiguredLoadBalancerFactory.java:114) ~[grpc-core-1.31.1.jar:1.31.1]
	at io.grpc.internal.ManagedChannelImpl$NameResolverListener$1NamesResolved.run(ManagedChannelImpl.java:1458) ~[grpc-core-1.31.1.jar:1.31.1]
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95) ~[grpc-api-1.33.0.jar:1.33.0]
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127) ~[grpc-api-1.33.0.jar:1.33.0]
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider.get(ManagedChannelImpl.java:474) ~[grpc-core-1.31.1.jar:1.31.1]
	at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:258) ~[grpc-core-1.31.1.jar:1.31.1]
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:215) ~[grpc-core-1.31.1.jar:1.31.1]
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:332) ~[grpc-stub-1.33.0.jar:1.33.0]
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:306) ~[grpc-stub-1.33.0.jar:1.33.0]
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:218) ~[grpc-stub-1.33.0.jar:1.33.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:146) ~[grpc-stub-1.33.0.jar:1.33.0]
	at org.example.echo.proto.EchoServiceGrpc$EchoServiceBlockingStub.echo(EchoServiceGrpc.java:169) ~[main/:?]
	at org.example.echo.EchoServiceTest.test(EchoServiceTest.java:19) ~[test/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] <28 internal calls>
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?] <9 internal calls>
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?] <23 internal calls>

io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!

	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at org.example.echo.proto.EchoServiceGrpc$EchoServiceBlockingStub.echo(EchoServiceGrpc.java:169)
	at org.example.echo.EchoServiceTest.test(EchoServiceTest.java:19) <31 internal calls>
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) <9 internal calls>
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) <23 internal calls>
Caused by: java.lang.NoSuchFieldError: ATTR_LOAD_BALANCING_CONFIG
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.tryHandleResolvedAddresses(AutoConfiguredLoadBalancerFactory.java:114)
	at io.grpc.internal.ManagedChannelImpl$NameResolverListener$1NamesResolved.run(ManagedChannelImpl.java:1458)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider.get(ManagedChannelImpl.java:474)
	at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:258)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:215)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:332)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:306)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:218)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:146)
	... 67 more

2020-12-17 12:25:22.419  INFO [SpringContextShutdownHook||] serverfactory.GrpcServerLifecycle - gRPC server shutdown.
```

**Comment by ST-DDT** [comment] 2020-12-17 17:54
Thanks for the info. Will be fixed in the next release.

**Comment by SledgeHammer01** [comment] 2020-12-18 23:13
> Thanks for the info. Will be fixed in the next release.

@ST-DDT 

I am using the starter with Spring Boot 2.4.1 and 1.34.0 and it works fine, but it's not compatible with the recent grpc update to 1.34.1. I think they moved some namespaces around.

**Comment by ST-DDT** [comment] 2020-12-25 14:03
@skoret I didn't encounter that particular error on my side. From the stacktrace, I can tell that you use different grpc-java library versions.

* grpc-stub-1.33.0
* grpc-core-1.31.1
* grpc-api-1.33.0

Please make sure that all grpc-java libraries use the exact same version.
You can use the [grpc-bom](https://mvnrepository.com/artifact/io.grpc/grpc-bom/1.34.1) to avoid those issues in the future. Does this solve the issue for you?

I will bump the grpc-java versions in this library anyway.

**Closed** 2020-12-28 09:04 UTC
Labels: question

**Comment by sreenidhy** [comment] 2020-12-28 15:14
Thank you for the upgrade!
