### ISSUE TITLE
Spring Boot 3 support?

### ISSUE THREAD

**Issue by SledgeHammer01** [yidongnan/grpc-spring-boot-starter#900] opened 2023-06-06 01:34 UTC
Hi, is there going to be a Spring Boot 3 version?

**Comment by ST-DDT** [comment] 2023-06-06 12:04
Please note that Spring Boot is already supported via workaround: https://github.com/yidongnan/grpc-spring-boot-starter/pull/775/files
(not released yet, just add the files yourself)

Duplicate of https://github.com/yidongnan/grpc-spring-boot-starter/issues/778

**Closed by ST-DDT** 2023-06-06 12:04 UTC
Labels: question
