### ISSUE TITLE
CallCredentialsHelper. bearerAuth(Supplier) doesn't work

### ISSUE THREAD

**Issue by kalmar** [yidongnan/grpc-spring-boot-starter#677] opened 2022-05-08 12:20 UTC
https://github.com/yidongnan/grpc-spring-boot-starter/blame/v2.13.1.RELEASE/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/security/CallCredentialsHelper.java#L195

```java
    public static CallCredentials bearerAuth(final Supplier<String> tokenSource) {
        return authorizationHeader(() -> BEARER_AUTH_PREFIX + tokenSource);
    }
```

Obviously `.get()` is missed there and auth header contains `toString` from the supplier instead of the token 😄

**Comment by ST-DDT** [comment] 2022-05-08 19:05
This has already been fixed and will be in the next version.
https://github.com/yidongnan/grpc-spring-boot-starter/pull/642
Duplicate of #617

**Closed by ST-DDT** 2022-05-08 19:05 UTC
Labels: bug
